# Generated by Django 5.0.1 on 2024-02-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='file',
            field=models.FileField(upload_to='media/<django.db.models.fields.CharField>'),
        ),
    ]
