# Generated by Django 5.0.1 on 2024-02-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_resources_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
