# Generated by Django 5.0.1 on 2024-02-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_forum_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
