# Generated by Django 5.0.1 on 2024-02-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_forum_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='slug',
        ),
    ]
