# Generated by Django 5.0.1 on 2024-02-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_forum_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='like',
            new_name='likes',
        ),
    ]
