# Generated by Django 5.0.1 on 2024-02-19 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_comment_forum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dislike', models.BooleanField()),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dislikes', to='main.comment')),
                ('forum', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dislikes', to='main.forum')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('author', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Likes', to='main.comment')),
                ('forum', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Likes', to='main.forum')),
            ],
        ),
    ]
