# Generated by Django 5.0.1 on 2024-02-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_comment_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
