# Generated by Django 5.0.1 on 2024-02-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
