# Generated by Django 5.0.1 on 2024-03-10 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_forum_dislikes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='dislikes',
            field=models.ManyToManyField(null=True, related_name='disliked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forum',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
