# Generated by Django 5.0.3 on 2024-03-22 09:09

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=main.models.generate_unique_slug, max_length=200),
        ),
    ]
