# Generated by Django 5.0.3 on 2024-03-22 09:13

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=main.models.generate_unique_slug, max_length=200),
        ),
    ]
