# Generated by Django 5.0.3 on 2024-04-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='description',
            field=models.CharField(default='A file', max_length=100),
        ),
    ]
