# Generated by Django 5.0.3 on 2024-04-15 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_remove_subject_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.grade'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default='Apple', max_length=50),
        ),
    ]
