# Generated by Django 5.0.3 on 2024-04-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_resources_grade_alter_resources_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='A subject', max_length=50),
        ),
    ]
