# Generated by Django 5.0.1 on 2024-02-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.TextField(default='Selene'),
        ),
    ]
