# Generated by Django 5.0.1 on 2024-02-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='section',
            field=models.CharField(default='Selene', max_length=20),
        ),
    ]
